# -*- coding: utf-8 -*-
"""Cópia de Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hu29qb4axv7EYQdqMY8GrDdso7hWmEZE

# AURA - Predição de Aprovação de Empréstimos Bancários

PUC Minas - Ciência da Computação
Data Science e Big Data
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.impute import SimpleImputer

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    roc_auc_score,
    classification_report
)

from google.colab import files

uploaded = files.upload()

df = pd.read_csv('train_u6lujuX_CVtuZ9i.csv')

print("Registros:", df.shape[0])
print("Atributos:", df.shape[1])

df.head()

"""# Dataset Utilizado

Nome: Loan Prediction Problem Dataset

Fonte: Kaggle

Objetivo:
Prever a aprovação ou reprovação de empréstimos bancários.

Variável-alvo:
Loan_Status

Tipo do problema:
Classificação Binária

# Análise Estatística
"""

df.describe()

colunas_numericas = [
    'ApplicantIncome',
    'CoapplicantIncome',
    'LoanAmount',
    'Loan_Amount_Term'
]

for coluna in colunas_numericas:
    print(f'\n{coluna}')
    print("Média:", df[coluna].mean())
    print("Mediana:", df[coluna].median())
    print("Mínimo:", df[coluna].min())
    print("Máximo:", df[coluna].max())
    print("Desvio Padrão:", df[coluna].std())

"""## Distribuição da variável-alvo"""

sns.countplot(data=df, x='Loan_Status')
plt.title('Distribuição das Aprovações')
plt.show()

"""Observa-se que a maioria dos empréstimos presentes no dataset foi aprovada, indicando um leve desbalanceamento entre as classes.

# EDA
# Histórico de Crédito
"""

sns.countplot(
    data=df,
    x='Credit_History',
    hue='Loan_Status'
)

plt.show()

"""
#Área do Imóvel"""

sns.countplot(
    data=df,
    x='Property_Area',
    hue='Loan_Status'
)

plt.show()

"""# Distribuição da Renda"""

sns.histplot(df['ApplicantIncome'], bins=30)
plt.show()

"""# Pré-processamento dos Dados"""

df_modelo = df.copy()

df_modelo.drop('Loan_ID', axis=1, inplace=True)

df_modelo['Dependents'] = df_modelo['Dependents'].replace('3+', 3)

cat_cols = [
    'Gender',
    'Married',
    'Education',
    'Self_Employed',
    'Property_Area'
]

for col in cat_cols:
    df_modelo[col] = df_modelo[col].fillna(df_modelo[col].mode()[0])

num_cols = [
    'LoanAmount',
    'Loan_Amount_Term',
    'Credit_History'
]

for col in num_cols:
    df_modelo[col] = df_modelo[col].fillna(df_modelo[col].median())

df_modelo['TotalIncome'] = (
    df_modelo['ApplicantIncome']
    + df_modelo['CoapplicantIncome']
)

df_modelo['EMI'] = (
    df_modelo['LoanAmount']
    / df_modelo['Loan_Amount_Term']
)

df_modelo['Dependents'] = df_modelo['Dependents'].replace('3+', '3')

for col in df_modelo.columns:
    if df_modelo[col].dtype == 'object':
        df_modelo[col] = df_modelo[col].fillna('Desconhecido')
        df_modelo[col] = df_modelo[col].astype(str)

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in df_modelo.columns:
    if df_modelo[col].dtype == 'object':
        df_modelo[col] = le.fit_transform(df_modelo[col])

X = df_modelo.drop('Loan_Status', axis=1)
y = df_modelo['Loan_Status']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

"""# Modelo Base - Random Forest"""

modelo_base = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

modelo_base.fit(X_train, y_train)

pred = modelo_base.predict(X_test)

print("Acurácia:", accuracy_score(y_test,pred))
print("Precisão:", precision_score(y_test,pred))
print("Recall:", recall_score(y_test,pred))
print("F1:", f1_score(y_test,pred))

"""# Experimento 1

Hipótese:
Aumentar o número de árvores pode melhorar a generalização do modelo.
"""

modelo_exp1 = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

modelo_exp1.fit(X_train, y_train)

pred_exp1 = modelo_exp1.predict(X_test)

accuracy_exp1 = accuracy_score(y_test, pred_exp1)
precision_exp1 = precision_score(y_test, pred_exp1)
recall_exp1 = recall_score(y_test, pred_exp1)
f1_exp1 = f1_score(y_test, pred_exp1)

print("Acurácia (Experimento 1):", accuracy_exp1)
print("Precisão (Experimento 1):", precision_exp1)
print("Recall (Experimento 1):", recall_exp1)
print("F1 (Experimento 1):", f1_exp1)

"""# Experimento 2

Hipótese:
Limitar a profundidade reduz overfitting.
"""

modelo_exp2 = RandomForestClassifier(
    n_estimators=100,
    max_depth=5,
    random_state=42
)

modelo_exp2.fit(X_train, y_train)

pred_exp2 = modelo_exp2.predict(X_test)

accuracy_exp2 = accuracy_score(y_test, pred_exp2)
precision_exp2 = precision_score(y_test, pred_exp2)
recall_exp2 = recall_score(y_test, pred_exp2)
f1_exp2 = f1_score(y_test, pred_exp2)

print("Acurácia (Experimento 2):", accuracy_exp2)
print("Precisão (Experimento 2):", precision_exp2)
print("Recall (Experimento 2):", recall_exp2)
print("F1 (Experimento 2):", f1_exp2)

"""# Experimento 3

Hipótese:
Utilizar menos atributos mantém desempenho semelhante.
"""

features_exp3 = ['Gender', 'Dependents', 'Property_Area']
X_exp3 = X[features_exp3]

# Split the data for Experiment 3
X_train_exp3, X_test_exp3, y_train_exp3, y_test_exp3 = train_test_split(
    X_exp3, y, test_size=0.20, random_state=42
)

# Train a RandomForestClassifier for Experiment 3
modelo_exp3 = RandomForestClassifier(n_estimators=100, random_state=42)
modelo_exp3.fit(X_train_exp3, y_train_exp3)

# Make predictions
pred_exp3 = modelo_exp3.predict(X_test_exp3)

# Evaluate the model
accuracy_exp3 = accuracy_score(y_test_exp3, pred_exp3)
precision_exp3 = precision_score(y_test_exp3, pred_exp3)
recall_exp3 = recall_score(y_test_exp3, pred_exp3)
f1_exp3 = f1_score(y_test_exp3, pred_exp3)

print("Acurácia (Experimento 3):", accuracy_exp3)
print("Precisão (Experimento 3):", precision_exp3)
print("Recall (Experimento 3):", recall_exp3)
print("F1 (Experimento 3):", f1_exp3)

resultados = pd.DataFrame({
    "Experimento":["Modelo Base", "Experimento 3", "Experimento 1", "Experimento 2"],
    "Acurácia":[accuracy_score(y_test,pred), accuracy_exp3, accuracy_exp1, accuracy_exp2],
    "Precisão":[precision_score(y_test,pred), precision_exp3, precision_exp1, precision_exp2],
    "Recall":[recall_score(y_test,pred), recall_exp3, recall_exp1, recall_exp2],
    "F1":[f1_score(y_test,pred), f1_exp3, f1_exp1, f1_exp2]
})

resultados

"""## Conclusão

O projeto AURA demonstrou que algoritmos de aprendizado de máquina podem auxiliar no processo de aprovação de empréstimos bancários.

Os experimentos indicaram que o atributo Credit_History possui maior influência na decisão de aprovação. Entre os modelos avaliados, o Random Forest apresentou o melhor equilíbrio entre precisão e recall.

A engenharia de atributos, especialmente a criação da variável TotalIncome, contribuiu para melhorar a qualidade das previsões.

Apesar dos resultados satisfatórios, o conjunto de dados possui tamanho reduzido e apresenta desbalanceamento entre as classes, o que limita a capacidade de generalização do modelo.
"""